import api from './api'
const getAll = async () => ({
    data: [
        {
            id: 1,
            gender: "male",
            name: 'Dr. Ahmed Hassan',
            specialty: 'Cardiologist',
            qualification: 'MBBS, FCPS (Cardiology), MD',
            experience: 15,
            chamber: 'Square Hospitals',
            schedule: 'Sat–Thu: 5:00 PM - 8:00 PM',
            fee: 1500,
            rating: 4.9,
            reviews: 432,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop'
        },
        {
            id: 2,
            gender: "female",
            name: 'Dr. Farhana Rahman',
            specialty: 'Gynecologist',
            qualification: 'MBBS, FCPS (Gynecology)',
            experience: 12,
            chamber: 'United Hospital',
            schedule: 'Sun–Thu: 4:00 PM - 7:00 PM',
            fee: 1200,
            rating: 4.8,
            reviews: 289,
            verified: true,
            image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop'
        },
        {
            id: 3,
            gender: "male",
            name: 'Dr. Kamal Hossain',
            specialty: 'Neurologist',
            qualification: 'MBBS, FCPS, FRCP',
            experience: 18,
            chamber: 'Apollo Hospitals Dhaka',
            schedule: 'Daily: 6:00 PM - 9:00 PM',
            fee: 2000,
            rating: 4.9,
            reviews: 567,
            verified: true,
            image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop'
        },
        {
            id: 4,
            gender: "female",
            name: 'Dr. Nusrat Jahan',
            specialty: 'Pediatrician',
            qualification: 'MBBS, FCPS (Pediatrics)',
            experience: 10,
            chamber: 'Popular Diagnostic & Hospital',
            schedule: 'Sat–Thu: 3:00 PM - 6:00 PM',
            fee: 1000,
            rating: 4.7,
            reviews: 324,
            verified: true,
            image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop'
        },
        {
            id: 5,
            gender: "male",
            name: 'Dr. Mohammad Rafiq',
            specialty: 'General Surgeon',
            qualification: 'MBBS, MS (Surgery)',
            experience: 20,
            chamber: 'Evercare Hospital Dhaka',
            schedule: 'Mon, Wed, Fri: 10:00 AM - 1:00 PM',
            fee: 1800,
            rating: 4.6,
            reviews: 210,
            verified: true,
            image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=150&h=150&fit=crop'
        },
        {
            id: 6,
            gender: "female",
            name: 'Dr. Ayesha Siddiqua',
            specialty: 'Endocrinologist',
            qualification: 'MBBS, FCPS (Medicine), MD (Endocrinology)',
            experience: 11,
            chamber: 'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
            schedule: 'Tue & Thu: 4:00 PM - 7:00 PM',
            fee: 1400,
            rating: 4.8,
            reviews: 178,
            verified: true,
            image: 'https://images.unsplash.com/photo-1580281657525-54a8b1b9b8e8?w=150&h=150&fit=crop'
        },
        {
            id: 7,
            gender: "male",
            name: 'Dr. Imran Karim',
            specialty: 'Orthopedic Surgeon',
            qualification: 'MBBS, MS (Orthopedics)',
            experience: 16,
            chamber: 'Labaid Specialized Hospital',
            schedule: 'Mon–Fri: 5:00 PM - 8:00 PM',
            fee: 1600,
            rating: 4.7,
            reviews: 298,
            verified: true,
            image: 'https://images.unsplash.com/photo-1542736667-069246bdbc73?w=150&h=150&fit=crop'
        },
        {
            id: 8,
            gender: "female",
            name: 'Dr. Shampa Akter',
            specialty: 'Oncologist',
            qualification: 'MBBS, FCPS (Oncology)',
            experience: 14,
            chamber: 'National Institute of Cancer Research & Hospital (NICRH)',
            schedule: 'Wed & Sat: 2:00 PM - 5:00 PM',
            fee: 2200,
            rating: 4.9,
            reviews: 412,
            verified: true,
            image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&h=150&fit=crop'
        },
        {
            id: 9,
            gender: "male",
            name: 'Dr. Salman Rahman',
            specialty: 'Pulmonologist',
            qualification: 'MBBS, MD (Respiratory Medicine)',
            experience: 13,
            chamber: 'Ibn Sina Hospital',
            schedule: 'Tue–Thu: 6:00 PM - 8:00 PM',
            fee: 1300,
            rating: 4.6,
            reviews: 155,
            verified: true,
            image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=150&h=150&fit=crop'
        },
        {
            id: 10,
            gender: "female",
            name: 'Dr. Laila Begum',
            specialty: 'ENT Specialist',
            qualification: 'MBBS, FCPS (ENT)',
            experience: 9,
            chamber: 'Ibn Sina Diagnostic & Imaging',
            schedule: 'Sat–Thu: 11:00 AM - 2:00 PM',
            fee: 900,
            rating: 4.5,
            reviews: 98,
            verified: true,
            image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop'
        },
        {
            id: 11,
            name: 'Prof. Dr. Sanawar Hossain',
            specialty: 'Cardiology',
            qualification: 'MBBS, MD (Cardiology), FCPS',
            experience: 20,
            facilityId: 1,
            chamber: 'Square Hospital',
            address: '18/F, West Panthapath, Dhaka',
            schedule: 'Sat-Thu: 5:00 PM - 8:00 PM',
            fee: 2000,
            rating: 4.9,
            reviews: 567,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10616',
            email: 'cardio@squarehospital.com',
            specialization: ['Adult Cardiology', 'Interventional Cardiology', 'Heart Disease Prevention'],
            education: [
                'MBBS - Dhaka Medical College',
                'MD (Cardiology) - NICVD',
                'Fellowship - Singapore'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 12,
            name: 'Prof. Dr. Rehana Parveen',
            specialty: 'Gynecology',
            qualification: 'MBBS, FCPS (Gynecology & Obstetrics)',
            experience: 18,
            facilityId: 1,
            chamber: 'Square Hospital',
            address: '18/F, West Panthapath, Dhaka',
            schedule: 'Sat-Thu: 4:00 PM - 7:00 PM',
            fee: 1500,
            rating: 4.8,
            reviews: 432,
            verified: true,
            image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop',
            phone: '10616',
            specialization: ['High Risk Pregnancy', 'Gynecological Surgery', 'Infertility Treatment'],
            education: [
                'MBBS - Dhaka Medical College',
                'FCPS (Gynecology) - BCPS'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 13,
            name: 'Dr. Zillur Rahman',
            specialty: 'Neurosurgery',
            qualification: 'MBBS, FCPS (Surgery), MS (Neurosurgery)',
            experience: 22,
            facilityId: 1,
            chamber: 'Square Hospital',
            address: '18/F, West Panthapath, Dhaka',
            schedule: 'Sun-Thu: 6:00 PM - 9:00 PM',
            fee: 2500,
            rating: 4.9,
            reviews: 678,
            verified: true,
            image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop',
            phone: '10616',
            specialization: ['Brain Surgery', 'Spine Surgery', 'Neuro-oncology'],
            education: [
                'MBBS - Dhaka University',
                'FCPS (Surgery) - BCPS',
                'MS (Neurosurgery) - BSMMU'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 14,
            name: 'Dr. Nazmul Islam',
            specialty: 'Endocrinology',
            qualification: 'MBBS, Diploma in Internal Medicine (UK), MRCP',
            experience: 15,
            facilityId: 2,
            chamber: 'United Hospital',
            address: 'Plot 15, Road 71, Gulshan, Dhaka',
            schedule: 'Sat-Thu: 3:00 PM - 6:00 PM',
            fee: 1500,
            rating: 4.7,
            reviews: 345,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10666',
            specialization: ['Diabetes Management', 'Thyroid Disorders', 'Hormone Imbalances'],
            education: [
                'MBBS - Dhaka Medical College',
                'Diploma in Internal Medicine (UK)',
                'MRCP (UK)'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 15,
            name: 'Dr. Jahangir Kabir',
            specialty: 'Cardiac Surgery',
            qualification: 'MBBS, MS (Cardiothoracic Surgery)',
            experience: 25,
            facilityId: 2,
            chamber: 'United Hospital',
            address: 'Plot 15, Road 71, Gulshan, Dhaka',
            schedule: 'Sun-Thu: 5:00 PM - 8:00 PM',
            fee: 3000,
            rating: 4.9,
            reviews: 789,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10666',
            specialization: ['CABG', 'Valve Surgery', 'Congenital Heart Surgery'],
            education: [
                'MBBS - Dhaka University',
                'MS (Cardiothoracic Surgery) - Bangabandhu Medical University'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 16,
            name: 'Dr. Rashid Un Nabi',
            specialty: 'Oncology',
            qualification: 'MBBS, M.Phil (Radiotherapy)',
            experience: 16,
            facilityId: 2,
            chamber: 'United Hospital',
            address: 'Plot 15, Road 71, Gulshan, Dhaka',
            schedule: 'Sat-Thu: 4:00 PM - 7:00 PM',
            fee: 2000,
            rating: 4.8,
            reviews: 456,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10666',
            specialization: ['Radiation Oncology', 'Chemotherapy', 'Cancer Treatment'],
            education: [
                'MBBS',
                'M.Phil (Radiotherapy)',
                'IAEA Fellowship (Thailand)'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 17,
            name: 'Prof. Dr. Md. Shahabuddin Talukder',
            specialty: 'Cardiology',
            qualification: 'MBBS, D.Card, FCPS (Medicine)',
            experience: 28,
            facilityId: 3,
            chamber: 'Apollo Hospitals Dhaka',
            address: 'Plot 81, Block E, Bashundhara, Dhaka',
            schedule: 'Sat-Thu: 5:00 PM - 8:00 PM',
            fee: 2500,
            rating: 4.9,
            reviews: 890,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10678',
            specialization: ['Interventional Cardiology', 'Echocardiography', 'Heart Failure Management'],
            education: [
                'MBBS',
                'D.Card (Dhaka University)',
                'FCPS (Medicine)'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 18,
            name: 'Dr. Borhan Uddin Ahmad',
            specialty: 'Internal Medicine',
            qualification: 'MBBS (DMC), MRCP (UK), FRCP',
            experience: 20,
            facilityId: 3,
            chamber: 'Apollo Hospitals Dhaka',
            address: 'Plot 81, Block E, Bashundhara, Dhaka',
            schedule: 'Sun-Thu: 3:00 PM - 6:00 PM',
            fee: 1800,
            rating: 4.8,
            reviews: 567,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10678',
            specialization: ['General Medicine', 'Diabetes', 'Hypertension'],
            education: [
                'MBBS (Dhaka Medical College)',
                'MRCP (UK)',
                'FRCP Edinburgh'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 19,
            name: 'Dr. Gulshan Ara',
            specialty: 'Gynecology',
            qualification: 'MBBS, MCPS, MS (Obs./Gynae.)',
            experience: 14,
            facilityId: 3,
            chamber: 'Apollo Hospitals Dhaka',
            address: 'Plot 81, Block E, Bashundhara, Dhaka',
            schedule: 'Sat-Thu: 4:00 PM - 7:00 PM',
            fee: 1500,
            rating: 4.7,
            reviews: 423,
            verified: true,
            image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop',
            phone: '10678',
            specialization: ['Laparoscopic Surgery', 'Infertility', 'High Risk Pregnancy'],
            education: [
                'MBBS',
                'MCPS',
                'MS (Obs./Gynae.)',
                'Advanced training in Laparoscopy (India)'
            ],
            languages: ['Bengali', 'English']
        },
        {
            id: 20,
            name: 'Dr. Md. Nabiul Hassan (Rana)',
            specialty: 'Nephrology',
            qualification: 'MBBS (DMC), MD (Nephrology)',
            experience: 12,
            facilityId: 3,
            chamber: 'Apollo Hospitals Dhaka',
            address: 'Plot 81, Block E, Bashundhara, Dhaka',
            schedule: 'Sun-Thu: 5:00 PM - 8:00 PM',
            fee: 1600,
            rating: 4.7,
            reviews: 345,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop',
            phone: '10678',
            specialization: ['Kidney Disease', 'Dialysis', 'Transplant Nephrology'],
            education: [
                'MBBS (Dhaka Medical College)',
                'MD (Nephrology)'
            ],
            languages: ['Bengali', 'English']
        },
        
    ]
})
export default { getAll }
