import api from './api'
const getAll = async () => ({
    data: [
        {
            id: 1,
            gender: "male",
            name: 'Dr. Ahmed Hassan',
            specialty: 'Cardiologist',
            qualification: 'MBBS, FCPS (Cardiology), MD',
            experience: 15,
            chamber: 'Square Hospitals',
            schedule: 'Sat–Thu: 5:00 PM - 8:00 PM',
            fee: 1500,
            rating: 4.9,
            reviews: 432,
            verified: true,
            image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop'
        },
        {
            id: 2,
            gender: "female",
            name: 'Dr. Farhana Rahman',
            specialty: 'Gynecologist',
            qualification: 'MBBS, FCPS (Gynecology)',
            experience: 12,
            chamber: 'United Hospital',
            schedule: 'Sun–Thu: 4:00 PM - 7:00 PM',
            fee: 1200,
            rating: 4.8,
            reviews: 289,
            verified: true,
            image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop'
        },
        {
            id: 3,
            gender: "male",
            name: 'Dr. Kamal Hossain',
            specialty: 'Neurologist',
            qualification: 'MBBS, FCPS, FRCP',
            experience: 18,
            chamber: 'Apollo Hospitals Dhaka',
            schedule: 'Daily: 6:00 PM - 9:00 PM',
            fee: 2000,
            rating: 4.9,
            reviews: 567,
            verified: true,
            image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop'
        },
        {
            id: 4,
            gender: "female",
            name: 'Dr. Nusrat Jahan',
            specialty: 'Pediatrician',
            qualification: 'MBBS, FCPS (Pediatrics)',
            experience: 10,
            chamber: 'Popular Diagnostic & Hospital',
            schedule: 'Sat–Thu: 3:00 PM - 6:00 PM',
            fee: 1000,
            rating: 4.7,
            reviews: 324,
            verified: true,
            image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop'
        },
        {
            id: 5,
            gender: "male",
            name: 'Dr. Mohammad Rafiq',
            specialty: 'General Surgeon',
            qualification: 'MBBS, MS (Surgery)',
            experience: 20,
            chamber: 'Evercare Hospital Dhaka',
            schedule: 'Mon, Wed, Fri: 10:00 AM - 1:00 PM',
            fee: 1800,
            rating: 4.6,
            reviews: 210,
            verified: true,
            image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=150&h=150&fit=crop'
        },
        {
            id: 6,
            gender: "female",
            name: 'Dr. Ayesha Siddiqua',
            specialty: 'Endocrinologist',
            qualification: 'MBBS, FCPS (Medicine), MD (Endocrinology)',
            experience: 11,
            chamber: 'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
            schedule: 'Tue & Thu: 4:00 PM - 7:00 PM',
            fee: 1400,
            rating: 4.8,
            reviews: 178,
            verified: true,
            image: 'https://images.unsplash.com/photo-1580281657525-54a8b1b9b8e8?w=150&h=150&fit=crop'
        },
        {
            id: 7,
            gender: "male",
            name: 'Dr. Imran Karim',
            specialty: 'Orthopedic Surgeon',
            qualification: 'MBBS, MS (Orthopedics)',
            experience: 16,
            chamber: 'Labaid Specialized Hospital',
            schedule: 'Mon–Fri: 5:00 PM - 8:00 PM',
            fee: 1600,
            rating: 4.7,
            reviews: 298,
            verified: true,
            image: 'https://images.unsplash.com/photo-1542736667-069246bdbc73?w=150&h=150&fit=crop'
        },
        {
            id: 8,
            gender: "female",
            name: 'Dr. Shampa Akter',
            specialty: 'Oncologist',
            qualification: 'MBBS, FCPS (Oncology)',
            experience: 14,
            chamber: 'National Institute of Cancer Research & Hospital (NICRH)',
            schedule: 'Wed & Sat: 2:00 PM - 5:00 PM',
            fee: 2200,
            rating: 4.9,
            reviews: 412,
            verified: true,
            image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&h=150&fit=crop'
        },
        {
            id: 9,
            gender: "male",
            name: 'Dr. Salman Rahman',
            specialty: 'Pulmonologist',
            qualification: 'MBBS, MD (Respiratory Medicine)',
            experience: 13,
            chamber: 'Ibn Sina Hospital',
            schedule: 'Tue–Thu: 6:00 PM - 8:00 PM',
            fee: 1300,
            rating: 4.6,
            reviews: 155,
            verified: true,
            image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=150&h=150&fit=crop'
        },
        {
            id: 10,
            gender: "female",
            name: 'Dr. Laila Begum',
            specialty: 'ENT Specialist',
            qualification: 'MBBS, FCPS (ENT)',
            experience: 9,
            chamber: 'Ibn Sina Diagnostic & Imaging',
            schedule: 'Sat–Thu: 11:00 AM - 2:00 PM',
            fee: 900,
            rating: 4.5,
            reviews: 98,
            verified: true,
            image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop'
        }
    ]
})
export default { getAll }
