import api from './api'

const getAll = async () => {
  return {
    data: [
      {
        id: 1,
        name: 'Square Hospital',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Panthapath',
        address: '18/F, Bir Uttam Qazi Nuruzzaman Sarak, West Panthapath, Dhaka 1205',
        phone: '10616',
        additionalPhones: ['+88 02 8144400', '+88 01713377775'],
        email: 'info@squarehospital.com',
        website: 'www.squarehospital.com',
        rating: 4.8,
        reviews: 1247,
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400&h=300&fit=crop',
        services: [
          'Emergency 24/7',
          'ICU',
          'CCU',
          'Surgery',
          'Cardiology',
          'Neurology',
          'Oncology',
          'Pediatrics',
          'Gynecology',
          'Orthopedics',
          'Urology',
          'Gastroenterology',
          'Nephrology',
          'Dermatology',
          'ENT',
          'Ophthalmology'
        ],
        specialties: [
          'Cardiac Surgery',
          'Neurosurgery',
          'Cancer Treatment',
          'Kidney Transplant',
          'Liver Transplant',
          'Joint Replacement',
          'IVF',
          'Robotic Surgery'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        beds: 500,
        doctors: 300,
        consultationRooms: 110,
        insurance: ['Meghna', 'Green Delta', 'Pragati', 'Popular', 'Rupali'],
        established: 2006,
        description: 'Square Hospital Limited is a tertiary care hospital and the leading contributor to private healthcare services in Bangladesh since December 16, 2006. It is one of the ventures of Square Group, the country\'s top business conglomerate.',
        facilities: ['Air Ambulance', 'Helipad', 'USA Standard Housekeeping', 'Free WiFi', 'Cafeteria', 'Prayer Room', 'Parking'],
        accreditation: ['JCI Accredited'],
        emergencyContact: '+88 01713377773-5'
      },
      {
        id: 2,
        name: 'United Hospital Limited',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Gulshan',
        address: 'Plot 15, Road 71, Gulshan, Dhaka 1212',
        phone: '10666',
        additionalPhones: ['+88 02 8836000', '+88 02 8836444', '+88 01914 001234'],
        email: 'info@uhlbd.com',
        website: 'www.uhlbd.com',
        rating: 4.7,
        reviews: 982,
        image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400&h=300&fit=crop',
        services: [
          'Emergency',
          'Cancer Treatment',
          'Heart Surgery',
          'Orthopedics',
          'Pediatrics',
          'Gynecology',
          'Neurology',
          'Urology',
          'Gastroenterology',
          'Nephrology',
          'Oncology',
          'Dermatology',
          'ENT',
          'Pulmonology'
        ],
        specialties: [
          'Oncology',
          'Cardiology',
          'Orthopedics',
          'Neurosurgery',
          'Cardiac Surgery',
          'Endovascular Neurosurgery',
          'Cosmetic Dermatology'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        beds: 350,
        doctors: 220,
        insurance: ['Meghna', 'Popular', 'United', 'Green Delta'],
        established: 2006,
        description: 'United Hospital Limited was borne out of a vision to provide complete and one-stop healthcare solution to the people of Bangladesh. It is accredited by Joint Commission International (JCI).',
        facilities: ['Emergency Ambulance', 'ICU', 'NICU', 'Blood Bank', 'Pharmacy', 'Parking'],
        accreditation: ['JCI Accredited'],
        emergencyContact: '+88 01914 001232',
        fax: '+88 02 8836446'
      },
      {
        id: 3,
        name: 'Apollo Hospitals Dhaka',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Bashundhara',
        address: 'Plot 81, Block E, Bashundhara R/A, Dhaka 1229',
        phone: '10678',
        additionalPhones: ['+88 02 8401661', '+88 02 55037242', '09606-276555'],
        email: 'info@apollodhaka.com',
        website: 'www.apollodhaka.com',
        rating: 4.9,
        reviews: 1543,
        image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=400&h=300&fit=crop',
        services: [
          'Multi-specialty',
          'Emergency',
          'Critical Care',
          'Transplant',
          'Robotic Surgery',
          'Cardiology',
          'Neurology',
          'Oncology',
          'Orthopedics',
          'Gastroenterology',
          'Nephrology',
          'Urology',
          'Pediatrics',
          'Gynecology',
          'Dermatology'
        ],
        specialties: [
          'Liver Transplant',
          'Kidney Transplant',
          'Robotic Surgery',
          'Cardiac Surgery',
          'Neurosurgery',
          'Oncology',
          'Hematology',
          'Endoscopic Surgery'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        beds: 450,
        doctors: 310,
        insurance: ['All Major Insurance Companies Accepted'],
        established: 2005,
        description: 'Apollo Hospitals Dhaka is the only JCI Accredited 450-bed multi-disciplinary super-specialty tertiary care hospital in Bangladesh. It started operations on April 16, 2005, providing comprehensive healthcare with latest medical, surgical and diagnostic facilities.',
        facilities: ['1.5 Tesla MRI', '64 Slice CT Scan', 'Gamma Camera', 'Dialysis Unit', 'Lithotripsy', 'Blood Bank', 'Pharmacy', 'Cafeteria'],
        accreditation: ['JCI Accredited'],
        emergencyContact: '+88 02 8401679',
        fax: '+88 02 8401679',
        floorSpace: '435,000 sq ft'
      },

      {
        id: 4,
        name: 'Popular Diagnostic Centre',
        category: 'Diagnostic',
        city: 'Dhaka',
        area: 'Dhanmondi',
        address: 'House 16, Road 2, Dhanmondi R/A, Dhaka 1205',
        phone: '10636',
        additionalPhones: ['09666 787801', '+88 09613 787801'],
        email: 'info@populardiagnostic.com',
        website: 'www.populardiagnostic.com',
        rating: 4.6,
        reviews: 2341,
        image: 'https://images.unsplash.com/photo-1581594549595-35f6edc7b762?w=400&h=300&fit=crop',
        services: [
          'Blood Test',
          'X-Ray',
          'CT Scan',
          'MRI',
          'Ultrasound',
          'ECG',
          'Endoscopy',
          'Pathology',
          'Radiology',
          'Digital X-Ray',
          'Color Doppler',
          'Mammography',
          'Bone Density Test',
          'Health Checkup Packages',
          'Home Sample Collection'
        ],
        specialties: [
          'Advanced Pathology',
          'Digital Imaging',
          'Molecular Diagnostics',
          'Histopathology',
          'Cytology'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        homeService: true,
        established: 1983,
        description: 'Popular Diagnostic Centre started its journey in 1983 and has become a symbol of reliability and trust. It is accredited by Bangladesh Accreditation Board and offers comprehensive diagnostic services at affordable prices.',
        facilities: ['Multiple Branches', 'Home Collection', 'Online Reports', '24/7 Service', 'Parking'],
        accreditation: ['Bangladesh Accreditation Board (BAS)'],
        branches: ['Dhanmondi', 'Gulshan', 'Uttara', 'Mirpur', 'Shyamoli', 'Lalmatia']
      },
      {
        id: 5,
        name: 'Ibn Sina Diagnostic Centre',
        category: 'Diagnostic',
        city: 'Dhaka',
        area: 'Dhanmondi',
        address: 'House 48, Road 9/A, Dhanmondi, Dhaka 1209',
        phone: '02-9661034',
        additionalPhones: ['10606', '+88 02 9660015'],
        email: 'info@ibnsina.com.bd',
        website: 'www.ibnsina.com.bd',
        rating: 4.5,
        reviews: 1876,
        image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=400&h=300&fit=crop',
        services: [
          'Pathology',
          'Radiology',
          'ECG',
          'Endoscopy',
          'Digital X-Ray',
          'Ultrasound',
          'CT Scan',
          'MRI',
          'Mammography',
          'Blood Tests',
          'Urine Tests',
          'Hormone Tests',
          'Cardiac Tests',
          'Home Sample Collection'
        ],
        specialties: [
          'Clinical Pathology',
          'Histopathology',
          'Biochemistry',
          'Microbiology',
          'Immunology'
        ],
        hours: '7:00 AM - 11:00 PM',
        verified: true,
        homeService: true,
        established: 1980,
        description: 'Ibn Sina Diagnostic & Imaging Centre is one of the pioneer diagnostic centers in Bangladesh, providing quality diagnostic services since 1980.',
        facilities: ['Multiple Branches', 'Home Collection', 'Online Booking', 'Digital Reports', 'Parking'],
        branches: ['Dhanmondi', 'Kalabagan', 'Sylhet']
      },
      {
        id: 6,
        name: 'Labaid Diagnostic',
        category: 'Diagnostic',
        city: 'Dhaka',
        area: 'Dhanmondi',
        address: 'House 06, Road 04, Dhanmondi, Dhaka 1205',
        phone: '10606',
        additionalPhones: ['+88 09666710606'],
        email: 'info@labaidgroup.com',
        website: 'www.labaidgroup.com',
        rating: 4.7,
        reviews: 3124,
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400&h=300&fit=crop',
        services: [
          'Lab Tests',
          'Imaging',
          'Health Checkup',
          'COVID-19 Test',
          'Home Collection',
          'Digital X-Ray',
          'CT Scan',
          'MRI',
          'Ultrasound',
          'ECG',
          'Echocardiography',
          'Pathology',
          'Microbiology',
          'Biochemistry',
          'Hormone Tests'
        ],
        specialties: [
          'Molecular Diagnostics',
          'Advanced Imaging',
          'Cardiac Diagnostics',
          'Cancer Screening',
          'Genetic Testing'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        homeService: true,
        established: 1989,
        description: 'Labaid Diagnostics is a leading diagnostic service provider in Bangladesh with state-of-the-art facilities and a commitment to quality healthcare.',
        facilities: ['24/7 Service', 'Multiple Branches', 'Home Collection', 'Online Reports', 'Express Service', 'Parking'],
        branches: ['Dhanmondi', 'Gulshan', 'Banani', 'Uttara', 'Mirpur']
      },

      {
        id: 7,
        name: 'Evercare Hospital Dhaka',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Bashundhara',
        address: 'Plot 81, Block E, Bashundhara R/A, Dhaka 1229',
        phone: '10678',
        additionalPhones: ['+88 02 55037242'],
        email: 'info@evercarebd.com',
        website: 'www.evercarebd.com',
        rating: 4.8,
        reviews: 1234,
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=400&h=300&fit=crop',
        services: [
          'Emergency',
          'Cardiology',
          'Oncology',
          'Neurology',
          'Orthopedics',
          'Gynecology',
          'Pediatrics',
          'Urology',
          'Gastroenterology',
          'Nephrology',
          'Critical Care'
        ],
        specialties: [
          'Advanced Cardiac Care',
          'Cancer Treatment',
          'Neurosurgery',
          'Joint Replacement',
          'Minimally Invasive Surgery'
        ],
        hours: '24/7',
        verified: true,
        featured: true,
        beds: 450,
        doctors: 280,
        insurance: ['All Major Insurance'],
        established: 2005,
        description: 'Evercare Hospital Dhaka (formerly Apollo Hospitals) is a JCI accredited multi-specialty hospital providing world-class healthcare services.',
        accreditation: ['JCI Accredited']
      },
      {
        id: 8,
        name: 'Bangladesh Specialized Hospital',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Shyamoli',
        address: '21 Shyamoli, Mirpur Road, Dhaka 1207',
        phone: '09666-710678',
        additionalPhones: ['+88 02 9124222'],
        email: 'info@bshl.com.bd',
        website: 'www.bshl.com.bd',
        rating: 4.6,
        reviews: 876,
        image: 'https://images.unsplash.com/photo-1519494140681-8b17d830a3ec?w=400&h=300&fit=crop',
        services: [
          'Emergency',
          'Surgery',
          'Medicine',
          'Gynecology',
          'Pediatrics',
          'Cardiology',
          'Orthopedics',
          'Urology',
          'Neurology',
          'Gastroenterology'
        ],
        specialties: [
          'Laparoscopic Surgery',
          'Joint Replacement',
          'Cardiac Care',
          'Stroke Management'
        ],
        hours: '24/7',
        verified: true,
        beds: 250,
        doctors: 150,
        insurance: ['Meghna', 'Green Delta', 'Popular'],
        description: 'Bangladesh Specialized Hospital offers comprehensive healthcare services with modern facilities and experienced medical professionals.'
      },
      {
        id: 9,
        name: 'BIRDEM General Hospital',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Shahbag',
        address: '122 Kazi Nazrul Islam Avenue, Shahbag, Dhaka 1000',
        phone: '02-9661551',
        additionalPhones: ['+88 02 8616641'],
        email: 'info@birdem.org.bd',
        website: 'www.birdem.org.bd',
        rating: 4.5,
        reviews: 2134,
        image: 'https://images.unsplash.com/photo-1632833239869-a37e3a5806d2?w=400&h=300&fit=crop',
        services: [
          'Diabetes Care',
          'Endocrinology',
          'Nephrology',
          'Cardiology',
          'Neurology',
          'Eye Care',
          'Dental',
          'General Medicine',
          'Surgery',
          'Dialysis'
        ],
        specialties: [
          'Diabetes Management',
          'Diabetic Foot Care',
          'Kidney Disease',
          'Diabetic Eye Care',
          'Endocrine Disorders'
        ],
        hours: '24/7',
        verified: true,
        beds: 600,
        doctors: 400,
        established: 1980,
        description: 'BIRDEM (Bangladesh Institute of Research and Rehabilitation in Diabetes, Endocrine and Metabolic Disorders) is a premier specialized hospital for diabetes and related complications.'
      },
      {
        id: 10,
        name: 'Dhaka Medical College Hospital',
        category: 'Hospital',
        city: 'Dhaka',
        area: 'Shahbag',
        address: 'Bakshibazar, Dhaka 1000',
        phone: '02-55165088',
        additionalPhones: ['02-9663737'],
        email: 'info@dmch.gov.bd',
        rating: 4.2,
        reviews: 3456,
        image: 'https://images.unsplash.com/photo-1504439468489-c8920d796a29?w=400&h=300&fit=crop',
        services: [
          'Emergency',
          'Surgery',
          'Medicine',
          'Pediatrics',
          'Gynecology',
          'Orthopedics',
          'Cardiology',
          'Neurology',
          'Urology',
          'ENT',
          'Ophthalmology'
        ],
        specialties: [
          'Emergency Medicine',
          'Trauma Care',
          'Burn Unit',
          'Intensive Care'
        ],
        hours: '24/7',
        verified: true,
        beds: 2600,
        doctors: 500,
        established: 1946,
        description: 'Dhaka Medical College Hospital is the oldest and largest government medical college hospital in Bangladesh, providing comprehensive healthcare services.'
      }
    ]
  }
}

export default { getAll }
