const getAll = async () => {
    return {
        data: [
            {
                id: 101,
                name: "Lazz Pharma",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Dhanmondi",
                address: "House 5, Road 2, Dhanmondi, Dhaka",
                phone: "01777-700800",
                email: "info@lazzpharma.com",
                website: "www.lazzpharma.com",
                rating: 4.6,
                reviews: 456,
                image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
                services: [
                    "Prescription Medicines",
                    "OTC Drugs",
                    "Healthcare Products",
                    "Home Delivery",
                    "Online Ordering"
                ],
                hours: "24/7",
                verified: true,
                featured: true,
                homeDelivery: true,
                onlineOrdering: true,
                description:
                    "Lazz Pharma is a leading pharmacy chain in Bangladesh providing quality medicines and healthcare products.",
                branches: ["Dhanmondi", "Gulshan", "Banani", "Uttara", "Mirpur"]
            },
            {
                id: 102,
                name: "Meditrina Pharma",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Gulshan",
                address: "House 45, Road 11, Gulshan 1, Dhaka",
                phone: "01777-111111",
                email: "info@meditrina.com.bd",
                rating: 4.7,
                reviews: 567,
                image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop",
                services: [
                    "Medicines",
                    "Medical Equipment",
                    "Baby Care",
                    "Vitamins & Supplements",
                    "Home Delivery"
                ],
                hours: "8:00 AM - 11:00 PM",
                verified: true,
                homeDelivery: true,
                onlineOrdering: true,
                description:
                    "Meditrina Pharma offers a wide range of pharmaceutical products and healthcare services.",
                branches: ["Gulshan", "Banani", "Dhanmondi"]
            },

            // NEW REAL PHARMACY DATA
            {
                id: 103,
                name: "Popular Pharmacy",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Shantinagar",
                address: "32 Shantinagar, Dhaka",
                phone: "01912-555444",
                email: "contact@popularpharma.com",
                rating: 4.5,
                reviews: 623,
                image: "https://images.unsplash.com/photo-1584433144859-1fc3ab64a57d?w=400",
                services: ["Prescription Medicines", "Health Check", "OTC", "Home Delivery"],
                hours: "24/7",
                verified: true,
                homeDelivery: true,
                onlineOrdering: true,
                description: "Popular Pharmacy serves customers with genuine medicines and health support.",
                branches: ["Shantinagar", "Panthapath", "Mirpur"]
            },
            {
                id: 104,
                name: "Dhaka Pharmacy",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Mohammadpur",
                address: "Block C, Mohammadpur, Dhaka",
                phone: "01755-224466",
                email: "support@dhakapharmacy.com",
                rating: 4.3,
                reviews: 312,
                image: "https://images.unsplash.com/photo-1606813902781-8cf4c97f6a6a?w=400",
                services: ["Medicines", "OTC", "Supplements", "Basic Diagnostics"],
                hours: "9:00 AM - 12:00 AM",
                verified: true,
                homeDelivery: true,
                onlineOrdering: false,
                description: "Dhaka Pharmacy provides community health services and authentic medicines.",
                branches: ["Mohammadpur"]
            },
            {
                id: 105,
                name: "Health & Hope Pharmacy",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Mirpur",
                address: "Mirpur 10 Circle, Dhaka",
                phone: "01888-334422",
                email: "info@healthhope.com",
                rating: 4.8,
                reviews: 845,
                image: "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                services: ["Prescription Drugs", "Consultation", "Home Delivery"],
                hours: "24/7",
                verified: true,
                homeDelivery: true,
                onlineOrdering: true,
                description: "Top-rated pharmacy delivering trusted healthcare services.",
                branches: ["Mirpur", "Uttara"]
            },
            {
                id: 106,
                name: "Uttara Medicine Corner",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Uttara",
                address: "Sector 7, Uttara, Dhaka",
                phone: "01644-112233",
                email: "uttaramedicine@gmail.com",
                rating: 4.2,
                reviews: 214,
                image: "https://images.unsplash.com/photo-1584362917165-526a968579e8?w=400",
                services: ["OTC Drugs", "Cosmetics", "Baby Products"],
                hours: "7:00 AM - 12:00 AM",
                verified: false,
                homeDelivery: true,
                onlineOrdering: false,
                description: "A reliable pharmacy serving Uttara residents.",
                branches: ["Uttara"]
            },
            {
                id: 107,
                name: "City Care Pharmacy",
                category: "Pharmacy",
                city: "Chattogram",
                area: "GEC Circle",
                address: "GEC Circle, Chattogram",
                phone: "01877-558899",
                email: "citycarectg@gmail.com",
                rating: 4.4,
                reviews: 358,
                image: "https://images.unsplash.com/photo-1588747134265-44f6b6f9c73d?w=400",
                services: ["Medicines", "OTC", "Health Supplies"],
                hours: "9:00 AM - 11:00 PM",
                verified: true,
                homeDelivery: true,
                onlineOrdering: true,
                description: "Serving Chattogram residents with essential medicines.",
                branches: ["GEC", "Agrabad"]
            },
            {
                id: 108,
                name: "Apollo Pharmacy",
                category: "Pharmacy",
                city: "Dhaka",
                area: "Bashundhara",
                address: "Bashundhara R/A, Dhaka",
                phone: "01722-665544",
                email: "apollo@pharma.com.bd",
                rating: 4.6,
                reviews: 509,
                image: "https://images.unsplash.com/photo-1603394543775-6160d2a4c898?w=400",
                services: ["Prescription Medicines", "Lab Booking", "Home Delivery"],
                hours: "24/7",
                verified: true,
                homeDelivery: true,
                onlineOrdering: true,
                description: "A trusted pharmacy operating near Bashundhara residential area.",
                branches: ["Bashundhara"]
            },
            {
                id: 109,
                name: "Wellness Pharmacy",
                category: "Pharmacy",
                city: "Sylhet",
                area: "Zindabazar",
                address: "Zindabazar Main Road, Sylhet",
                phone: "01799-887766",
                email: "wellnesspharma@gmail.com",
                rating: 4.5,
                reviews: 412,
                image: "https://images.unsplash.com/photo-1612277794497-17a2df5520b8?w=400",
                services: ["OTC", "Prescription", "Health Products"],
                hours: "8:00 AM - 12:00 AM",
                verified: true,
                homeDelivery: true,
                onlineOrdering: false,
                description: "A popular pharmacy for Sylhet residents.",
                branches: ["Zindabazar"]
            },
            {
                id: 110,
                name: "Prime Care Pharmacy",
                category: "Pharmacy",
                city: "Khulna",
                area: "Shibbari",
                address: "Shibbari Circle, Khulna",
                phone: "01755-990011",
                email: "primecarekhulna@gmail.com",
                rating: 4.1,
                reviews: 187,
                image: "https://images.unsplash.com/photo-1584313369741-8897a0d1a5c7?w=400",
                services: ["Medicines", "OTC", "First Aid"],
                hours: "9:00 AM - 10:00 PM",
                verified: false,
                homeDelivery: false,
                onlineOrdering: false,
                description: "Trusted neighborhood pharmacy in Khulna.",
                branches: ["Shibbari"]
            },
            {
                id: 2000,
                name: "Al-amin Pharmacy Point",
                category: "Pharmacy",
                city: "Moulvibazar",
                area: "Rajnagar",
                address: "House 94, Road 25, Rajnagar, Moulvibazar",
                phone: "01768308412",
                email: "al-aminpharmacypoi2000@example.com",
                website: "www.al-aminpharmacypoint.com",
                rating: 4.8,
                reviews: 140,
                image: "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                services: [
                    "Prescription Medicines",
                    "Immunizations",
                    "Health Check",
                    "Home Delivery"
                ],
                hours: "7:00 AM - 12:00 AM",
                verified: true,
                featured: false,
                homeDelivery: true,
                onlineOrdering: false,
                description: "Al-amin Pharmacy Point provides trusted medicines and healthcare services in Rajnagar, Moulvibazar.",
                branches: [
                    "Rajnagar",
                    "Sadar"
                ]
            },
            {
                id: 2001,
                "name": "Nurul Huda Pharmacy Plus",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Sadar",
                "address": "House 195, Road 33, Sadar, Moulvibazar",
                "phone": "01865930983",
                "email": "nurulhudapharmacypl2001@example.com",
                "website": "",
                "rating": 4.3,
                "reviews": 379,
                "image": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop",
                "services": [
                    "OTC Drugs",
                    "First Aid",
                    "Health Supplies"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Nurul Huda Pharmacy Plus provides trusted medicines and healthcare services in Sadar, Moulvibazar.",
                "branches": [
                    "Sadar"
                ]
            },
            {
                id: 2002,
                "name": "Sakib Medicine House Pharma",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar",
                "address": "House 7, Road 37, Shamshernagar, Kamalganj",
                "phone": "01428470908",
                "email": "sakibmedicinehouseph2002@example.com",
                "website": "",
                "rating": 4.8,
                "reviews": 420,
                "image": "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
                "services": [
                    "Prescription Medicines",
                    "OTC Drugs",
                    "Home Delivery"
                ],
                "hours": "24/7",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Sakib Medicine House Pharma provides trusted medicines and healthcare services in Shamshernagar, Kamalganj.",
                "branches": [
                    "Shamshernagar",
                    "Near Hospital"
                ]
            },
            {
                id: 2003,
                "name": "Shamsher Pharmacy Plus",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar Bazaar",
                "address": "House 63, Road 6, Shamshernagar Bazaar, Kamalganj",
                "phone": "01288581297",
                "email": "shamsherpharmacypl2003@example.com",
                "website": "",
                "rating": 4.0,
                "reviews": 508,
                "image": "https://images.unsplash.com/photo-1606813902781-8cf4c97f6a6a?w=400",
                "services": [
                    "Medicines",
                    "Medical Equipment",
                    "Basic Diagnostics",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": false,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Shamsher Pharmacy Plus provides trusted medicines and healthcare services in Shamshernagar Bazaar, Kamalganj.",
                "branches": [
                    "Shamshernagar Bazaar"
                ]
            },
            {
                id: 2004,
                "name": "Noorani Pharmacy Center",
                "category": "Pharmacy",
                "city": "Sylhet",
                "area": "Zindabazar",
                "address": "House 33, Road 5, Zindabazar, Sylhet",
                "phone": "01744576031",
                "email": "nooranipharmacycen2004@example.com",
                "website": "www.nooranipharmacycenter.com",
                "rating": 4.6,
                "reviews": 73,
                "image": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a57d?w=400",
                "services": [
                    "Prescription Medicines",
                    "Vitamins & Supplements",
                    "Baby Care",
                    "Home Delivery"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Noorani Pharmacy Center provides trusted medicines and healthcare services in Zindabazar, Sylhet.",
                "branches": [
                    "Zindabazar",
                    "Bazaar"
                ]
            },
            {
                id: 2005,
                "name": "Rahman Medical Pharmacy",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Sreemangal",
                "address": "House 107, Road 9, Sreemangal, Moulvibazar",
                "phone": "01328970455",
                "email": "rahmanmedicalpharm2005@example.com",
                "website": "",
                "rating": 4.1,
                "reviews": 841,
                "image": "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                "services": [
                    "OTC Drugs",
                    "First Aid",
                    "Health Supplies"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Rahman Medical Pharmacy provides trusted medicines and healthcare services in Sreemangal, Moulvibazar.",
                "branches": [
                    "Sreemangal"
                ]
            },
            {
                id: 2006,
                "name": "Anwar Pharmacy Medical",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Barlekha",
                "address": "House 72, Road 16, Barlekha, Moulvibazar",
                "phone": "01710553704",
                "email": "anwarpharmacymedic2006@example.com",
                "website": "",
                "rating": 4.3,
                "reviews": 206,
                "image": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop",
                "services": [
                    "Prescription Medicines",
                    "Online Ordering",
                    "Home Delivery"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Anwar Pharmacy Medical provides trusted medicines and healthcare services in Barlekha, Moulvibazar.",
                "branches": [
                    "Barlekha",
                    "Sadar"
                ]
            },
            {
                id: 2007,
                "name": "Moulvi Pharmacy Plus",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar R/A",
                "address": "House 47, Road 29, Shamshernagar R/A, Kamalganj",
                "phone": "01912345678",
                "email": "moulvipharmacypl2007@example.com",
                "website": "",
                "rating": 3.9,
                "reviews": 477,
                "image": "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
                "services": [
                    "Medicines",
                    "Medical Equipment",
                    "Basic Diagnostics",
                    "Home Delivery"
                ],
                "hours": "24/7",
                "verified": false,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Moulvi Pharmacy Plus provides trusted medicines and healthcare services in Shamshernagar R/A, Kamalganj.",
                "branches": [
                    "Shamshernagar R/A"
                ]
            },
            {
                id: 2008,
                "name": "Shultana Pharmacy Center",
                "category": "Pharmacy",
                "city": "Sylhet",
                "area": "Bagbazar",
                "address": "House 2, Road 11, Bagbazar, Sylhet",
                "phone": "01733722190",
                "email": "shultanapharmacycen2008@example.com",
                "website": "",
                "rating": 4.2,
                "reviews": 236,
                "image": "https://images.unsplash.com/photo-1606813902781-8cf4c97f6a6a?w=400",
                "services": [
                    "Prescription Medicines",
                    "Vitamins & Supplements",
                    "Baby Care",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Shultana Pharmacy Center provides trusted medicines and healthcare services in Bagbazar, Sylhet.",
                "branches": [
                    "Bagbazar"
                ]
            },
            {
                id: 2009,
                "name": "Faruque Medical Pharmacy",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Sadar",
                "address": "House 20, Road 41, Sadar, Moulvibazar",
                "phone": "01688123456",
                "email": "faruquemedicalph2009@example.com",
                "website": "",
                "rating": 4.2,
                "reviews": 98,
                "image": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a57d?w=400",
                "services": [
                    "OTC Drugs",
                    "First Aid",
                    "Health Supplies"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Faruque Medical Pharmacy provides trusted medicines and healthcare services in Sadar, Moulvibazar.",
                "branches": [
                    "Sadar"
                ]
            },
            {
                id: 2010,
                "name": "Islamia Pharmacy Care",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar",
                "address": "House 11, Road 2, Shamshernagar, Kamalganj",
                "phone": "01799887766",
                "email": "islamipharmacycare2010@example.com",
                "website": "",
                "rating": 4.6,
                "reviews": 412,
                "image": "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                "services": [
                    "Prescription Medicines",
                    "OTC Drugs",
                    "Home Delivery"
                ],
                "hours": "24/7",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Islamia Pharmacy Care provides trusted medicines and healthcare services in Shamshernagar, Kamalganj.",
                "branches": [
                    "Shamshernagar"
                ]
            },
            {
                id: 2011,
                "name": "Rabbani Pharmacy Point",
                "category": "Pharmacy",
                "city": "Sylhet",
                "area": "Mirabazar",
                "address": "House 88, Road 3, Mirabazar, Sylhet",
                "phone": "01766554433",
                "email": "rabbanipharmacypoi2011@example.com",
                "website": "",
                "rating": 4.1,
                "reviews": 421,
                "image": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop",
                "services": [
                    "Medicines",
                    "Medical Equipment",
                    "Basic Diagnostics",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Rabbani Pharmacy Point provides trusted medicines and healthcare services in Mirabazar, Sylhet.",
                "branches": [
                    "Mirabazar"
                ]
            },
            {
                id: 2012,
                "name": "Amin Clinic Pharmacy Center",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Kamalganj",
                "address": "House 56, Road 8, Kamalganj, Moulvibazar",
                "phone": "01644112233",
                "email": "aminclinicpharmacyc2012@example.com",
                "website": "",
                "rating": 3.9,
                "reviews": 214,
                "image": "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                "services": [
                    "OTC Drugs",
                    "Cosmetics",
                    "Baby Products"
                ],
                "hours": "7:00 AM - 12:00 AM",
                "verified": false,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Amin Clinic Pharmacy Center provides trusted medicines and healthcare services in Kamalganj, Moulvibazar.",
                "branches": [
                    "Kamalganj"
                ]
            },
            {
                id: 2013,
                "name": "Shahjalal Pharmacy Plus",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Sadar",
                "address": "House 3, Road 19, Sadar, Moulvibazar",
                "phone": "01722333444",
                "email": "shahjalalpharmacypl2013@example.com",
                "website": "www.shahjalalpharmacyplus.com",
                "rating": 4.5,
                "reviews": 633,
                "image": "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
                "services": [
                    "Prescription Medicines",
                    "Vitamins & Supplements",
                    "Baby Care",
                    "Home Delivery"
                ],
                "hours": "24/7",
                "verified": true,
                "featured": true,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Shahjalal Pharmacy Plus provides trusted medicines and healthcare services in Sadar, Moulvibazar.",
                "branches": [
                    "Sadar",
                    "Near Hospital"
                ]
            },
            {
                id: 2014,
                "name": "GreenCare Pharmacy",
                "category": "Pharmacy",
                "city": "Sylhet",
                "area": "Kotbari",
                "address": "House 121, Road 2, Kotbari, Sylhet",
                "phone": "01755677899",
                "email": "greencarepharmacy2014@example.com",
                "website": "",
                "rating": 4.4,
                "reviews": 142,
                "image": "https://images.unsplash.com/photo-1606813902781-8cf4c97f6a6a?w=400",
                "services": [
                    "Prescription Medicines",
                    "Online Ordering",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "GreenCare Pharmacy provides trusted medicines and healthcare services in Kotbari, Sylhet.",
                "branches": [
                    "Kotbari"
                ]
            },
            {
                id: 2015,
                "name": "Shafi Pharmacy Center",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar",
                "address": "House 15, Road 4, Shamshernagar, Kamalganj",
                "phone": "01744990011",
                "email": "shafipharmacycen2015@example.com",
                "website": "",
                "rating": 4.6,
                "reviews": 55,
                "image": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a57d?w=400",
                "services": [
                    "Medicines",
                    "Medical Equipment",
                    "Basic Diagnostics",
                    "Home Delivery"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Shafi Pharmacy Center provides trusted medicines and healthcare services in Shamshernagar, Kamalganj.",
                "branches": [
                    "Shamshernagar"
                ]
            },
            {
                id: 2016,
                "name": "Azad Pharmacy Medical",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Mirabazar",
                "address": "House 54, Road 14, Mirabazar, Moulvibazar",
                "phone": "01799112233",
                "email": "azadpharmacymed2016@example.com",
                "website": "",
                "rating": 4.2,
                "reviews": 299,
                "image": "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop",
                "services": [
                    "Prescription Medicines",
                    "Vitamins & Supplements",
                    "Baby Care",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Azad Pharmacy Medical provides trusted medicines and healthcare services in Mirabazar, Moulvibazar.",
                "branches": [
                    "Mirabazar"
                ]
            },
            {
                id: 2017,
                "name": "Central Medicine Pharmacy",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Shantinagar",
                "address": "House 169, Road 8, Shantinagar, Moulvibazar",
                "phone": "01206585112",
                "email": "centralmedicine2017@example.com",
                "website": "",
                "rating": 4.9,
                "reviews": 12,
                "image": "https://images.unsplash.com/photo-1584277263222-11a4f78a0c83?w=400",
                "services": [
                    "Prescription Medicines",
                    "OTC Drugs",
                    "Home Delivery"
                ],
                "hours": "7:00 AM - 12:00 AM",
                "verified": true,
                "featured": true,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "Central Medicine Pharmacy provides trusted medicines and healthcare services in Shantinagar, Moulvibazar.",
                "branches": [
                    "Shantinagar",
                    "Panthapath"
                ]
            },
            {
                id: 2018,
                "name": "Community Pharmacy Plus",
                "category": "Pharmacy",
                "city": "Sylhet",
                "area": "Ambarkhana",
                "address": "House 39, Road 21, Ambarkhana, Sylhet",
                "phone": "01733445566",
                "email": "communitypharmacypl2018@example.com",
                "website": "",
                "rating": 4.4,
                "reviews": 275,
                "image": "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop",
                "services": [
                    "Medicines",
                    "Medical Equipment",
                    "Basic Diagnostics",
                    "Home Delivery"
                ],
                "hours": "8:00 AM - 10:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Community Pharmacy Plus provides trusted medicines and healthcare services in Ambarkhana, Sylhet.",
                "branches": [
                    "Ambarkhana"
                ]
            },
            {
                id: 2019,
                "name": "TrustCare Pharmacy",
                "category": "Pharmacy",
                "city": "Moulvibazar",
                "area": "Dhanmondi",
                "address": "House 14, Road 12, Dhanmondi, Moulvibazar",
                "phone": "01788990077",
                "email": "trustcarepharmacy2019@example.com",
                "website": "",
                "rating": 4.4,
                "reviews": 523,
                "image": "https://images.unsplash.com/photo-1606813902781-8cf4c97f6a6a?w=400",
                "services": [
                    "Prescription Medicines",
                    "OTC Drugs",
                    "Home Delivery"
                ],
                "hours": "9:00 AM - 11:00 PM",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": false,
                "description": "TrustCare Pharmacy provides trusted medicines and healthcare services in Dhanmondi, Moulvibazar.",
                "branches": [
                    "Dhanmondi"
                ]
            },
            {
                id: 2020,
                "name": "Hira Pharmacy Point",
                "category": "Pharmacy",
                "city": "Kamalganj",
                "area": "Shamshernagar",
                "address": "House 200, Road 1, Shamshernagar, Kamalganj",
                "phone": "01700111222",
                "email": "hirapharmacypoin2020@example.com",
                "website": "",
                "rating": 4.0,
                "reviews": 334,
                "image": "https://images.unsplash.com/photo-1584433144859-1fc3ab64a57d?w=400",
                "services": [
                    "Prescription Medicines",
                    "Vitamins & Supplements",
                    "Baby Care",
                    "Home Delivery"
                ],
                "hours": "24/7",
                "verified": true,
                "featured": false,
                "homeDelivery": true,
                "onlineOrdering": true,
                "description": "Hira Pharmacy Point provides trusted medicines and healthcare services in Shamshernagar, Kamalganj.",
                "branches": [
                    "Shamshernagar",
                    "Near Hospital"
                ]
            },
        ]
    };
};

export default { getAll };
